### ISSUE TITLE
Running one of the pre defined experiements raises exceptions

### ISSUE THREAD

**Issue by zwurgl** [dkmfbk/dket#20]
Hi, thanks for providing that interesting repo.

When installing it on my Ubuntu 18 with python3 and the following versions of the relevant packages (installing liteflow from github gives me a version 0.0.3 whereas in the dket setup.py a version 0.1.0 is mentioned ...)  

$ pip3 freeze | grep -iE '(lite|tensor)'
liteflow==0.0.3
tensorboard==1.12.2
tensorboardX==1.2
tensorflow-gpu==1.12.0

I am getting a lot of exceptions when launching one of the stored experiments: 
  python3 ./bin/dket-experiment-run --config experiments/2k-closed.json

Traceback (most recent call last):
  File "./bin/dket-experiment-run", line 45, in <module>
    runtime.Experiment.load(CONFIG, logdir=ARGS.logdir, force=ARGS.force).run()
  File "/usr/local/lib/python3.6/dist-packages/dket-0.0.1-py3.6.egg/dket/runtime.py", line 190, in load
[....]
 File "/usr/local/lib/python3.6/dist-packages/liteflow/utils.py", line 41, in as_scope
    return next(tf.variable_scope(scope).gen)  # pylint: disable=I0011,E1101
AttributeError: 'variable_scope' object has no attribute 'gen'

Any idea where my error could be or what to do about it?

**Comment by petrux** [comment]
First thing coming on top of my head: you are using a newer TensorFlow version. 
As specified in the `README.md`, the best way to go is to run everything in the proper virtual environment. You can get it following the steps:

```
:~$ git clone git@github.com:dkmfbk/dket.git
:~$ cd dket
:~$ ./bin/dket-venv-setup gpu
```

the `./bin/dket-venv-setup` will install the proper TensorFlow version, which is the `1.2.0`---while you are using the `1.12.0`.

**Comment by zwurgl** [comment]
I see! Thanks a lot. Will try! 

Best regards!
